# usage:
# $ docker build --build-arg "USER=someuser" --tag test .
# $ docker run --rm test

FROM ethereum/client-go:latest

ARG USER=appuser
ARG ACCOUNT_PASSWORD=5uper53cr3t
ENV HOME /home/$USER

RUN apk add --no-cache git bash python3
RUN ln -s /usr/bin/python3 /usr/bin/python
# dev image only
RUN apk add --update sudo
###

# RUN npm i -g solc
# RUN npm i -g truffle
# RUN npm i -g ganache

# Install Glide
# RUN go get -u github.com/Masterminds/glide/...

# Generate a new account for the ethereum blockchain
# WARN: DO NOT SHARE THE PASSWROD! DO NOT FOGET PASSWORD.
# RUN echo ${ACCOUNT_PASSWORD} > /tmp/password && \
#    geth account new --password /tmp/password \
#    && rm -f /tmp/password

# User config for dev
RUN adduser -D $USER \
   && echo "$USER ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/$USER \
   && chmod 0440 /etc/sudoers.d/$USER

# non-dev user
# RUN addgroup -S appgroup && adduser -S appuser -G appgroup

USER $USER
WORKDIR $HOME

CMD ["/bin/bash"]