# ref: https://medium.com/scb-digital/running-a-private-ethereum-blockchain-using-docker-589c8e6a4fe8

version: '3.7'

services:
  geth-bootnode:
    hostname: geth-bootnode
    env_file:
      - .env
    image: geth-client
    build:
      context: .
      args:
        - ACCOUNT_PASSWORD=${ACCOUNT_PASSWORD}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - ./data/boot:/root/.ethereum
    command:
      --nodekeyhex=${NODE_KEY_HEX}
      --nodiscover
      --ipcdisable
      --networkid=${NETWORK_ID}
      --netrestrict=${NETRESTRICT}
    networks:
      priv-eth-net:

  geth-rpc-endpoint:
    hostname: geth-rpc-endpoint
    env_file:
      - .env
    image: geth-client
    depends_on:
      - geth-bootnode
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - ./data/rpc:/root/.ethereum
    # --allow-insecure-unlock is for dev only. remove it for production.
    # allow unlocking the account we created over the http. unsafe.
    command:
      --bootnodes=${BOOT_NODE}
      --allow-insecure-unlock
      --http
      --http.addr="0.0.0.0"
      --http.api="eth,web3,net,admin,personal"
      --http.corsdomain="*"
      --networkid=${NETWORK_ID}
      --netrestrict=${NETRESTRICT}
      --ws
      --ws.port=8546
      --ws.addr=0.0.0.0
      --ws.origins="*"
      --ws.api="admin,db,eth,miner,web3,net,personal,txpool,debug"
    ports:
      - 8545:8545
    networks:
      priv-eth-net:

  geth-miner:
    hostname: geth-miner
    env_file:
      - .env
    image: geth-client
    depends_on:
      - geth-bootnode
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - ./data/miner:/root/.ethereum
    command:
      --bootnodes=${BOOT_NODE}
      --mine
      --miner.threads=1
      --networkid=${NETWORK_ID}
      --netrestrict=${NETRESTRICT}
    networks:
      priv-eth-net:

networks:
  priv-eth-net:
    driver: bridge
    ipam:
      config:
      - subnet: ${NETRESTRICT}