# FROM ethereum/client-go:latest

FROM alpine:3.15.0

ARG USER=appuser
ENV HOME /home/$USER

RUN apk add --no-cache go \
   geth nodejs npm openssh \
   git sudo python3 bash bash-completion
RUN ln -s /usr/bin/python3 /usr/bin/python

RUN npm i -g solc
# RUN npm i -g truffle
# RUN npm i -g ganache

# Install Glide
# RUN go get -u github.com/Masterminds/glide/...

# Generate a new account for the ethereum blockchain
# WARN: DO NOT SHARE THE PASSWROD! DO NOT FOGET PASSWORD.
# RUN echo ${ACCOUNT_PASSWORD} > /tmp/password && \
#    geth account new --password /tmp/password \
#    && rm -f /tmp/password

# User config for dev
RUN adduser -D $USER \
   && echo "$USER ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/$USER \
   && chmod 0440 /etc/sudoers.d/$USER

# non-dev user
# RUN addgroup -S appgroup && adduser -S appuser -G appgroup

USER $USER
WORKDIR $HOME

CMD [ "/bin/bash" ]